openapi: 3.0.3
info:
  title: API AEGHIS
  description: API para gestión de usuarios y recursos del sistema AEGHIS
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo
  - url: https://api.aegis.com
    description: Servidor de producción

tags:

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Introduce el token JWT para autenticación

  schemas:


security:
  - JWT: []

paths: