spring.datasource.url=jdbc:postgresql://localhost:5432/aegisdb
spring.datasource.username=aegis
spring.datasource.password=aegisdatabase
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.docker.compose.enabled=false

# Configuración de SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# application.yml
clerk.jwks-url=https://tight-polecat-94.clerk.accounts.dev/.well-known/jwks.json
clerk.issuer=https://tight-polecat-94.clerk.accounts.dev

# Logging para depuración
logging.level.com.tuapp.security=DEBUG
logging.level.org.springframework.security=INFO

# Desactivar la página de error de Whitelabel
# server.error.whitelabel.enabled=false

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
logging.level.com.tfg.aegis=DEBUG

# Configuración de Google Api
google.places.api.key=AIzaSyDTX3fLb3rgNb0oQNHk7M0eU-hXuBQuWAM

#Open-in-view
spring.jpa.open-in-view=false

# Clave invitations
invitation.aes.key=OnKz7pqU6/pC5Z/rw6JtL1LnLYvQfjKaGC4u4OryTMU=