# =============================
# DATASOURCE (Supabase)
# =============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================
# JPA / Hibernate
# =============================
spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL

# =============================
# Clerk Auth
# =============================
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.issuer=${CLERK_ISSUER}

# =============================
# APIs externas
# =============================
google.maps.api.key=${GOOGLE_MAPS_API_KEY}
invitation.aes.key=${INVITATION_AES_KEY}

# Email Configuration
app.admin.emails=${APP_ADMIN_EMAILS}
app.admin.secret=${APP_ADMIN_SECRET}

# =============================
# Logging (solo lo \u00FAtil)
# =============================
logging.level.com.tfg.aegis=INFO
logging.level.org.springframework.web=INFO

# =============================
# Hikari Pool ( Heroku + Supabase)
# =============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.keepalive-time=30000