# valor por defecto para tu entorno local
spring.profiles.active=dev

# Base de Datos PostgreSQL
# =============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# =============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false

# Docker Compose (desactivado)
# =============================
spring.docker.compose.enabled=false

# Swagger / Springdoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Clerk Auth Config
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.issuer=${CLERK_ISSUER}

# Logging
logging.level.com.tuapp.security=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
logging.level.com.tfg.aegis=DEBUG

# Google Places API
google.maps.api.key=${GOOGLE_PLACES_API_KEY}

invitation.aes.key=${INVITATION_AES_KEY}

# Email Configuration
app.admin.emails=${APP_ADMIN_EMAILS}
app.admin.secret=${APP_ADMIN_SECRET}

